const items = [
  [
    {
      id: "1",
      pic: "/images/8.jpg",
      title: "MAS TSHIRT",
      price: "150dh",
      rate: "4.5",
      review: "0",
    },
    {
      id: "2",
      pic: "/images/5.jpg",
      title: "HUSA TSHIRT",
      price: "250dh",
      rate: "5",
      review: "2",
    },
    {
      id: "3",
      pic: "/images/6.jpg",
      title: "IRT TSHIRT",
      price: "150dh",
      rate: "4.5",
      review: "0",
    },
    {
      id: "4",
      pic: "/images/1.jpg",
      title: "RAJA TSHIRT",
      price: "150dh",
      rate: "4.5",
      review: "0",
    },
    {
      id: "5",
      pic: "/images/10.jpg",
      title: "WAC TSHIRT",
      price: "150dh",
      rate: "4.5",
      review: "10",
    },
    {
      id: "6",
      pic: "/images/11.jpeg",
      title: "WAC TSHIRT",
      price: "150dh",
      rate: "4.5",
      review: "10",
    },{
      id: "7",
      pic: "/images/3.png",
      title: "FAR TSHIRT",
      price: "150dh",
      rate: "4.5",
      review: "10",
    },
  ],
  [
    {
      id: "12",
      pic: "/images/12.jpg",
      title: "MAS Hoodie",
      price: "350dh",
      rate: "5",
      review: "8",
    },
    {
      id: "8",
      pic: "/images/14.png",
      title: "HUSA Hoodie",
      price: "350dh",
      rate: "5",
      review: "2",
    },
    {
      id: "9",
      pic: "/images/13.jpg",
      title: "IRT Hoodie",
      price: "350dh",
      rate: "4.0",
      review: "0",
    },
    {
      id: "10",
      pic: "/images/7.jpg",
      title: "RAJA Hoodie",
      price: "350dh",
      rate: "4.5",
      review: "0",
    },
    {
      id: "11",
      pic: "/images/2.png",
      title: "WAC Hoodie",
      price: "350dh",
      rate: "5",
      review: "10",
    },
  ],
  [
    {
      id: "4",
      pic: "/images/1.jpg",
      title: "RAJA T-shirt",
      price: "150dh",
      rate: "4.5",
      review: "0",
    },
    {
      id: "11",
      pic: "/images/2.png",
      title: "HOODIE WAC",
      price: "250dh",
      rate: "4.5",
      review: "1",
    },
    {
      id: "",
      pic: "/images/3.png",
      title: "FAR T-shirt",
      price: "250dh",
      rate: "4.5",
      review: "1",
    },
    {
      id: "",
      pic: "/images/4.jpg",
      title: "CAGOULE",
      price: "70dh",
      rate: "4",
      review: "3",
    },
  ],
  [
    {
      pic: "/images/5.jpg",
      title: "HUSA TSHIRT",
      price: "250dh",
      rate: "5",
      review: "2",
    },
    {
      pic: "/images/6.jpg",
      title: "IRT TSHIRT",
      price: "150dh",
      rate: "4.5",
      review: "0",
    },
    {
      pic: "/images/1.jpg",
      title: "TSHIRT RAJA",
      price: "150dh",
      rate: "4.5",
      review: "0",
    },
    {
      pic: "/images/2.png",
      title: "HOODIE WAC",
      price: "250dh",
      rate: "4.5",
      review: "1",
    },
    {
      pic: "/images/3.png",
      title: "HOODIE WAC",
      price: "250dh",
      rate: "4.5",
      review: "1",
    },
    {
      pic: "/images/4.jpg",
      title: "CAGOULE",
      price: "70dh",
      rate: "4",
      review: "3",
    },
  ],
  [
    {
      description: "lorem",
      id: "6",
      pic: "/images/11.jpeg",
      title: "WAC TSHIRT",
      price: "150dh",
      rate: "4.5",
      review: "10",
    },{
    description: "lorem",
    id: "7",
    pic: "/images/3.png",
    title: "FAR TSHIRT",
    price: "150dh",
    rate: "4.5",
    review: "10",
  },
    {
      description: "lorem",
      id: "12",
      pic: "/images/12.jpg",
      title: "MAS Hoodie",
      price: "350dh",
      rate: "5",
      review: "8",
    },
    {
      description: "lorem",
      id: "8",
      pic: "/images/14.png",
      title: "HUSA Hoodie",
      price: "350dh",
      rate: "5",
      review: "2",
    },
    {
      description: "lorem",
      id: "9",
      pic: "/images/13.jpg",
      title: "IRT Hoodie",
      price: "350dh",
      rate: "4.0",
      review: "0",
    },
    {
      description: "lorem",
      id: "10",
      pic: "/images/7.jpg",
      title: "RAJA Hoodie",
      price: "350dh",
      rate: "4.5",
      review: "0",
    },
    {
      description: "lorem",
      id: "11",
      pic: "/images/2.png",
      title: "WAC Hoodie",
      price: "350dh",
      rate: "5",
      review: "10",
    },
    {
      description: "lorem",
      id: "1",
      pic: "/images/8.jpg",
      title: "MAS TSHIRT",
      price: "150dh",
      lowprice: "199dh",
      rate: "4.5",
      review: "0",
    },
    {
      description: "lorem",
      id: "2",
      pic: "/images/5.jpg",
      title: "HUSA TSHIRT",
      price: "250dh",
      lowprice: "299dh",
      rate: "5",
      review: "2",
    },
    {
      description: "lorem",
      id: "3",
      pic: "/images/6.jpg",
      title: "IRT TSHIRT",
      price: "150dh",
      lowprice: "199dh",
      rate: "4.5",
      review: "0",
    },
    {
      description: "lorem",
      id: "4",
      pic: "/images/1.jpg",
      title: "RAJA TSHIRT",
      price: "150dh",
      lowprice: "199dh",
      rate: "4.5",
      review: "0",
    },
    {
      description: "lorem",
      id: "5",
      pic: "/images/10.jpg",
      title: "WAC TSHIRT",
      price: "150dh",
      lowprice: "199dh",
      rate: "4.5",
      review: "10",
    },
  ]
];
export default items;
